import type { Metadata } from "next";

// import localFont from "next/font/local";
import { Saira } from "next/font/google";

import "./globals.css";

import NavbarDesktop from "@/components/navbar";
import { navigationItems } from "@/data/navbarItems";
import Footer from "@/components/footer";
import ContactPopover from "@/components/contactPopover";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

// const specialGothicExtendedBold = localFont({
//   src: "../public/fonts/SpecialGothicExtendedBold.woff2",
//   display: "swap",
//   variable: "--font-special",
// });

export const metadata: Metadata = {
  title: "Medihelix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${saira.variable}  antialiased overflow-x-hidden`}>
        <NavbarDesktop items={navigationItems} />
        {children}
        <Footer />
        <ContactPopover />
      </body>
    </html>
  );
}
